import React, { useState } from 'react';

const AppStoreScreen = () => {
    const [activeTab, setActiveTab] = useState('Communication');

    const categories = [
        "Communication", "Social", "Video", "Music", "Gaming",
        "Shopping", "Payment", "Travel", "Productivity",
        "Education", "Utility", "Health", "Photo"
    ];

    const apps = {
        "Communication": [
            { title: "WhatsApp", url: "https://www.whatsapp.com" },
            { title: "Telegram", url: "https://telegram.org" },
            { title: "Signal", url: "https://signal.org" },
            { title: "Messenger", url: "https://www.messenger.com" },
            { title: "Viber", url: "https://www.viber.com" },
            { title: "Discord", url: "https://discord.com" },
            { title: "Snapchat", url: "https://www.snapchat.com" },
            { title: "WeChat", url: "https://www.wechat.com" },
            { title: "LINE", url: "https://line.me" }
        ],
        "Social": [
            { title: "Instagram", url: "https://www.instagram.com" },
            { title: "Facebook", url: "https://www.facebook.com" },
            { title: "X (Twitter)", url: "https://x.com" },
            { title: "Snapchat", url: "https://www.snapchat.com" },
            { title: "Threads", url: "https://www.threads.com" },
            { title: "LinkedIn", url: "https://linkedin.com" },
            { title: "Reddit", url: "https://www.reddit.com" },
            { title: "Pinterest", url: "https://pinterest.com" },
            { title: "Tumblr", url: "https://www.tumblr.com" },
            { title: "YouTube", url: "https://www.youtube.com" },
            { title: "TikTok", url: "https://www.tiktok.com" },
            { title: "Douyin", url: "https://www.douyin.com" },
            { title: "Kuaishou", url: "https://www.kuaishou.com" },
            { title: "Weibo", url: "https://m.weibo.cn" },
            { title: "QQ", url: "https://www.qq.com" },
            { title: "Qzone", url: "https://qzone.qq.com" },
            { title: "VK", url: "https://vk.com" },
            { title: "Quora", url: "https://www.quora.com" },
            { title: "Bilibili", url: "https://www.bilibili.com" },
            { title: "Xiaohongshu", url: "https://www.xiaohongshu.com" },
            { title: "Douban", url: "https://m.douban.com/movie" },
            { title: "Baidu Tieba", url: "https://c.tieba.baidu.com" },
            { title: "Twitch", url: "https://www.twitch.tv" },
            { title: "Line", url: "https://www.line.me" },
            { title: "Likee", url: "https://likee.video/en/index?lang=es" },
            { title: "Zhihu", url: "https://www.zhihu.com" },
            { title: "Medium", url: "https://medium.com" },
            { title: "Yelp", url: "https://www.yelp.com" },
            { title: "Nextdoor", url: "https://nextdoor.com" },
            { title: "MySpace", url: "https://myspace.com" },
            { title: "Badoo", url: "https://badoo.com" },
            { title: "Meetup", url: "https://www.meetup.com" },
            { title: "Flickr", url: "https://www.flickr.com" },
            { title: "Xing", url: "https://www.xing.com" },
            { title: "Mastodon", url: "https://joinmastodon.org" },
            { title: "Bluesky", url: "https://bsky.app" },
            { title: "9GAG", url: "https://9gag.com" },
            { title: "Roposo", url: "https://www.roposo.com" },
            { title: "Dribbble", url: "https://dribbble.com" },
            { title: "Vine", url: "https://vine.co" },
            { title: "Hi5", url: "https://hi5.com" },
            { title: "Rutube", url: "https://rutube.ru" },
            { title: "Renren", url: "https://www.renren.com" },
            { title: "Youku Tudou", url: "https://youku.com" },
            { title: "Zoom", url: "https://zoom.us" },
            { title: "Meet", url: "https://meet.google.com" },
            { title: "imo", url: "https://imo.im" },
            { title: "Picsart", url: "https://picsart.com" }
        ],
        "Video": [
            { title: "YouTube", url: "https://www.youtube.com" },
            { title: "Netflix", url: "https://www.netflix.com" },
            { title: "Prime Video", url: "https://www.amazon.com/gp/video/offers/ref=atv_pv_new_offer" },
            { title: "Disney+ Hotstar", url: "https://www.disneyplus.com" },
            { title: "Twitch", url: "https://www.twitch.tv" },
            { title: "Tubi", url: "https://tubitv.com" },
            { title: "HBO Max", url: "https://www.max.com" },
            { title: "Peacock TV", url: "https://www.peacocktv.com" },
            { title: "Paramount Plus", url: "https://www.paramountplus.com" },
            { title: "Crunchyroll", url: "https://www.crunchyroll.com" },
            { title: "CuriosityStream", url: "https://www.kqzyfj.com/click-5226272-12658720" },
            { title: "fuboTV", url: "https://www.fubo.tv/welcome?irad=343747&irmp=1410335" },
            { title: "Pluto TV", url: "https://pluto.tv" },
            { title: "TiviMate", url: "https://play.google.com/store/apps/details?id=ar.tvplayer.tv&hl=en_US&gl=US" },
            { title: "Airy TV", url: "https://live.airy.tv/Featured/8_Warzone" },
            { title: "VUit", url: "https://www.vuit.com" },
            { title: "TikiLive", url: "https://www.tikilive.com" },
            { title: "KlowdTV", url: "https://www.klowdtv.com" },
            { title: "LocalBTV", url: "https://www.localbtv.com" },
            { title: "DistroTV", url: "https://www.distro.tv" },
            { title: "Herogo TV", url: "https://www.herogotv.com" },
            { title: "Showtime PPV", url: "https://www.sho.com/sports/fights" },
            { title: "DAZN", url: "https://www.dazn.com/en-US/home" },
            { title: "CBS Sports", url: "https://www.cbssports.com" },
            { title: "FOX Sports", url: "https://www.foxsports.com" },
            { title: "Downloader", url: "https://play.google.com/store/apps/details?id=com.esaba.downloader&hl=en_US&gl=US" },
            { title: "MX Player", url: "https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad&hl=en_US&gl=US" },
            { title: "Amazon Silk", url: "https://www.amazon.com/Amazon-com-Amazon-Silk-Web-Browser/dp/B01M35MQV4" },
            { title: "VLC", url: "https://www.videolan.org" },
            { title: "VirusTotal", url: "https://www.virustotal.com" },
            { title: "Hulu", url: "https://www.hulu.com/welcome" },
            { title: "Sling TV", url: "https://sling-tv.pxf.io/c/10915/2902023/14334" },
            { title: "DIRECTV", url: "https://www.jdoqocy.com/click-5226272-17074389" },
            { title: "17Live", url: "https://17live.com" },
            { title: "AcFun", url: "https://acfun.cn" }
        ],
        "Music": [
            { title: "Spotify", url: "https://www.spotify.com" },
            { title: "Apple Music", url: "https://www.apple.com/apple-music" },
            { title: "YouTube Music", url: "https://music.youtube.com" },
            { title: "SoundCloud", url: "https://soundcloud.com" },
            { title: "Gaana", url: "https://gaana.com" },
            { title: "SiriusXM", url: "https://www.siriusxm.com" },
            { title: "Tidal", url: "https://tidal.com" },
            { title: "Amazon Music Unlimited", url: "https://www.amazon.com/music/unlimited" },
            { title: "LiveOne", url: "https://www.liveone.com" },
            { title: "Deezer", url: "https://www.deezer.com" },
            { title: "Qobuz", url: "https://www.qobuz.com" },
            { title: "iHeart Radio", url: "https://www.iheart.com" },
            { title: "AccuRadio", url: "https://www.accuradio.com" },
            { title: "Amazon Music", url: "https://music.amazon.com" },
            { title: "Anghami", url: "https://www.anghami.com" },
            { title: "Audiomack", url: "https://audiomack.com" },
            { title: "Bandcamp", url: "https://bandcamp.com" },
            { title: "Boomplay", url: "https://www.boomplay.com" },
            { title: "hoopla", url: "https://www.hoopladigital.com" },
            { title: "Jango", url: "https://www.jango.com" },
            { title: "Joox", url: "https://www.joox.com" },
            { title: "KKBox", url: "https://www.kkbox.com" },
            { title: "Line Music", url: "https://music.line.me" },
            { title: "Melon", url: "https://www.melon.com" },
            { title: "Moov", url: "https://www.moov.hk" },
            { title: "Music Choice", url: "https://www.musicchoice.com" },
            { title: "MyTuner Radio", url: "https://www.mytuner-radio.com" },
            { title: "Napster", url: "https://napster.com" },
            { title: "NetEase Cloud Music", url: "https://music.163.com" },
            { title: "Pandora", url: "https://www.pandora.com" },
            { title: "Patari", url: "https://www.patari.com" },
            { title: "ROKK", url: "https://rokk-app.com" },
            { title: "Stingray Music", url: "https://www.stingray.com" },
            { title: "TuneIn", url: "https://tunein.com" },
            { title: "VIBE", url: "https://vibe.naver.com" },
            { title: "Wolfgang's", url: "https://www.wolfgangs.com" },
            { title: "IDAGIO", url: "https://www.idagio.com" }
        ],
        "Gaming": [
            { title: "MONOPOLY GO!", url: "https://www.similarweb.com/app/google/com.scopely.monopolygo/" },
            { title: "NYT Games", url: "https://www.similarweb.com/app/google/com.nytimes.crossword/" },
            { title: "Candy Crush Saga", url: "https://www.similarweb.com/app/google/com.king.candycrushsaga/" },
            { title: "Water Sorter", url: "https://www.similarweb.com/app/google/com.gimica.watersorter/" },
            { title: "Pin Master", url: "https://www.similarweb.com/app/google/com.pinmaster.screwpuzzle/" },
            { title: "Color Dots", url: "https://www.similarweb.com/app/google/com.gimica.spaceconnect/" },
            { title: "Treasure Master", url: "https://www.similarweb.com/app/google/com.gimica.treasuremaster/" },
            { title: "Chess Online", url: "https://www.similarweb.com/app/google/com.chess/" },
            { title: "Slam Dunk!", url: "https://www.similarweb.com/app/google/com.gimica.slamdunk/" },
            { title: "Wooden Puzzle", url: "https://www.similarweb.com/app/google/com.gimica.zentiles/" },
            { title: "Disney Solitaire", url: "https://www.similarweb.com/app/google/com.superplaystudios.disneysolitairedreams/" },
            { title: "Threadform", url: "https://www.similarweb.com/app/google/com.gimica.threadform/" },
            { title: "Tile Match Pro", url: "https://www.similarweb.com/app/google/com.gimica.tilematchpro/" },
            { title: "Pokémon TCG Pocket", url: "https://www.similarweb.com/app/google/jp.pokemon.pokemontcgp/" },
            { title: "Word Kitchen", url: "https://www.similarweb.com/app/google/com.gimica.wordkitchen/" },
            { title: "Hex Match", url: "https://www.similarweb.com/app/google/com.gimica.hexmatch/" },
            { title: "Puzzle Pop", url: "https://www.similarweb.com/app/google/com.gimica.puzzlepopblaster/" },
            { title: "Brawl Stars", url: "https://www.similarweb.com/app/google/com.supercell.brawlstars/" },
            { title: "Solitaire Verse", url: "https://www.similarweb.com/app/google/com.gimica.solitaireverse/" },
            { title: "Bingo Card", url: "https://www.similarweb.com/app/google/com.miniit.bingo/" },
            { title: "Merge Blast", url: "https://www.similarweb.com/app/google/com.gimica.mergeblast/" },
            { title: "Fish of Fortune", url: "https://www.similarweb.com/app/google/com.whalo.games.fishoffortune/" },
            { title: "8 Ball Pool", url: "https://www.similarweb.com/app/google/com.miniclip.eightballpool/" },
            { title: "Block Hole Clash", url: "https://www.similarweb.com/app/google/com.gimica.blockholeclash/" },
            { title: "Coin Master", url: "https://www.similarweb.com/app/google/com.moonactive.coinmaster/" },
            { title: "Royal Kingdom", url: "https://www.similarweb.com/app/google/com.dreamgames.royalkingdom/" },
            { title: "Unravel Master", url: "https://www.similarweb.com/app/google/com.gdrhrhw.utxdm/" },
            { title: "Frosty Reel", url: "https://www.similarweb.com/app/google/com.forsty.reel.slot/" },
            { title: "Vita Mahjong", url: "https://www.similarweb.com/app/google/com.vitastudio.mahjong/" },
            { title: "Slide & Roll", url: "https://www.similarweb.com/app/google/com.gimica.slideandroll/" },
            { title: "Tangram Heaven", url: "https://www.similarweb.com/app/google/com.gimica.tangram/" },
            { title: "Associations", url: "https://www.similarweb.com/app/google/games.burny.associations.word.puzzle/" },
            { title: "Bingo Dice", url: "https://www.similarweb.com/app/google/com.funcraft.bingodice/" },
            { title: "Free Fire", url: "https://www.similarweb.com/app/google/com.dts.freefireth/" },
            { title: "Spiral Drop", url: "https://www.similarweb.com/app/google/com.gimica.helixdash/" },
            { title: "Mad Smash", url: "https://www.similarweb.com/app/google/com.gimica.madsmash/" },
            { title: "Gossip Harbor", url: "https://www.similarweb.com/app/google/com.mergegames.gossipharbor/" },
            { title: "Water Sort Puz", url: "https://www.similarweb.com/app/google/com.playvalve.watersort/" },
            { title: "Best Guess Live", url: "https://www.similarweb.com/app/google/com.netflix.NGP.BestGuess/" },
            { title: "Hexa Sort", url: "https://www.similarweb.com/app/google/com.gamebrain.hexasort/" },
            { title: "Spades Stars", url: "https://www.similarweb.com/app/google/com.playvalve.spades/" },
            { title: "Discord", url: "https://discord.com" },
            { title: "Royal Kingdom", url: "https://www.singular.net/blog/top-mobile-games/" },
            { title: "Vita Mahjong", url: "https://www.singular.net/blog/top-mobile-games/" }
        ],
        "Shopping": [
            { title: "Amazon", url: "https://www.amazon.com" },
            { title: "Snapdeal", url: "https://snapdeal.com" },
            { title: "eBay", url: "https://www.ebay.com" },
            { title: "OLX", url: "https://olx.in" },
            { title: "Walmart", url: "https://www.walmart.com" },
            { title: "Temu", url: "https://www.temu.com" },
            { title: "SHEIN", url: "https://www.shein.com" },
            { title: "Target", url: "https://www.target.com" },
            { title: "AliExpress", url: "https://www.aliexpress.com" },
            { title: "Ad It Up", url: "https://www.play2pay.com" },
            { title: "Fetch", url: "https://www.fetch.com" },
            { title: "Shop", url: "https://www.shopify.com" },
            { title: "Sam's Club", url: "https://www.samsclub.com" },
            { title: "Etsy", url: "https://www.etsy.com" },
            { title: "Costco", url: "https://www.costco.com" },
            { title: "Benjamin", url: "https://www.benjamin.com" },
            { title: "Walgreens", url: "https://www.walgreens.com" },
            { title: "Kroger", url: "https://www.kroger.com" },
            { title: "Home Depot", url: "https://www.homedepot.com" },
            { title: "Frisbee", url: "https://www.klover.com" },
            { title: "Circle K", url: "https://www.circlek.com" },
            { title: "Pogo", url: "https://www.pogo.com" },
            { title: "Best Buy", url: "https://www.bestbuy.com" },
            { title: "OfferUp", url: "https://www.offerup.com" },
            { title: "Alibaba", url: "https://www.alibaba.com" },
            { title: "Bridge", url: "https://www.bridgemoney.com" },
            { title: "Dollar General", url: "https://www.dollargeneral.com" },
            { title: "Lowe's", url: "https://www.lowes.com" },
            { title: "Klarna", url: "https://www.klarna.com" },
            { title: "Afterpay", url: "https://www.afterpay.com" },
            { title: "Whatnot", url: "https://www.whatnot.com" },
            { title: "Poshmark", url: "https://www.poshmark.com" },
            { title: "My H-E-B", url: "https://www.heb.com" },
            { title: "Mercari", url: "https://www.mercari.com" },
            { title: "Safeway", url: "https://www.safeway.com" },
            { title: "Meijer", url: "https://www.meijer.com" },
            { title: "Ibotta", url: "https://www.ibotta.com" },
            { title: "Groupon", url: "https://www.groupon.com" },
            { title: "Kohl's", url: "https://www.kohls.com" },
            { title: "Receipt Hog", url: "https://www.receipthog.com" },
            { title: "CoinOut", url: "https://www.coinout.com" },
            { title: "Macy's", url: "https://www.macys.com" },
            { title: "BJ's", url: "https://www.bjs.com" },
            { title: "Wayfair", url: "https://www.wayfair.com" },
            { title: "Nike", url: "https://www.nike.com" },
            { title: "Instacart", url: "https://www.instacart.com" }
        ],
        "Payment": [
            { title: "PayPal", url: "https://www.paypal.com" },
            { title: "Apple Pay", url: "https://www.apple.com" },
            { title: "Google Wallet", url: "http://www.google.com/wallet/business/index.html" },
            { title: "Cash App", url: "https://square.sjv.io/c/10915/2003298/9398" },
            { title: "Venmo", url: "https://venmo.sjv.io/c/10915/877880/12053" },
            { title: "Samsung Wallet", url: "https://www.samsung.com/us/samsung-pay/" }
        ],
        "Travel": [
            { title: "Google Maps", url: "https://maps.google.com" },
            { title: "Uber", url: "https://play.google.com/store/apps/details?id=com.ubercab" },
            { title: "Airbnb", url: "https://www.airbnb.com" },
            { title: "Google Travel", url: "https://www.google.com/travel" },
            { title: "Hopper", url: "https://apps.apple.com/us/app/hopper-flight-hotel-deals/id904052407" },
            { title: "Roadtrippers", url: "https://roadtrippers.com/about/app" },
            { title: "TripIt", url: "https://apps.apple.com/us/app/tripit-travel-planner/id311035142" },
            { title: "Booking.com", url: "https://www.booking.com" },
            { title: "Busbud", url: "https://www.busbud.com" },
            { title: "Culture Trip", url: "https://theculturetrip.com/our-app" },
            { title: "Expedia", url: "https://www.expedia.com" },
            { title: "Hotels.com", url: "https://www.hotels.com" },
            { title: "Hotel Tonight", url: "https://apps.apple.com/us/app/hoteltonight-hotel-deals/id407690035" },
            { title: "Hotwire", url: "https://apps.apple.com/us/app/hotwire/id566635048" },
            { title: "Kayak", url: "https://www.kayak.com" },
            { title: "Orbitz", url: "https://www.orbitz.com" },
            { title: "Priceline", url: "https://www.priceline.com" },
            { title: "Roomer Travel", url: "https://apps.apple.com/us/app/roomer-travel/id877222676" },
            { title: "Viator", url: "https://apps.apple.com/us/app/viator-tours-activities/id434832826" },
            { title: "Vrbo", url: "https://www.vrbo.com/mobile" },
            { title: "Wanderu", url: "https://www.wanderu.com/en-us/app" },
            { title: "Glamping Hub", url: "https://glampinghub.com" },
            { title: "Harvest Hosts", url: "https://harvesthosts.com" },
            { title: "Hipcamp", url: "https://www.hipcamp.com" },
            { title: "Pitchup", url: "https://www.pitchup.com/en-us" },
            { title: "The Dyrt", url: "https://thedyrt.com" },
            { title: "Happy Cow", url: "https://www.happycow.net" },
            { title: "Lonely Planet", url: "http://www.lonelyplanet.com" },
            { title: "Rick Steves", url: "https://www.ricksteves.com/watch-read-listen/audio/audio-europe" },
            { title: "Tripadvisor", url: "https://www.tripadvisor.com" },
            { title: "Yelp", url: "https://www.yelp.com" },
            { title: "AllTrails", url: "https://www.alltrails.com/mobile" },
            { title: "GasBuddy", url: "https://www.gasbuddy.com/App" },
            { title: "Google Translate", url: "https://play.google.com/store/apps/details?id=com.google.android.apps.translate" },
            { title: "iExit", url: "https://iexitapp.com" },
            { title: "Wanderlog", url: "https://wanderlog.com" },
            { title: "Tripsy", url: "https://tripsy.app" },
            { title: "Polarsteps", url: "https://polarsteps.com" }
        ],
        "Productivity": [
            { title: "Google Drive", url: "https://www.google.com/drive" },
            { title: "Slack", url: "https://slack.com" },
            { title: "Todoist", url: "https://todoist.com" },
            { title: "Google Calendar", url: "https://calendar.google.com" },
            { title: "Calendly", url: "https://calendly.com" },
            { title: "Reclaim", url: "http://reclaim.ai" },
            { title: "Apple Notes", url: "https://www.icloud.com/notes" },
            { title: "Fireflies", url: "https://fireflies.ai" },
            { title: "Freedom", url: "https://freedom.to" },
            { title: "Sunsama", url: "https://sunsama.com" },
            { title: "Toggl Track", url: "https://toggl.com" },
            { title: "Pomodor", url: "https://pomodor.app/timer" },
            { title: "Habitica", url: "https://habitica.com" },
            { title: "Instapaper", url: "https://www.instapaper.com" },
            { title: "Outlook", url: "https://www.microsoft.com/en-us/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook" },
            { title: "Beeper", url: "https://www.beeper.com" },
            { title: "Clipboard", url: "https://www.microsoft.com/en-us/windows/tips/clipboard-history" },
            { title: "Feedly", url: "https://feedly.com" },
            { title: "Loom", url: "https://www.loom.com" },
            { title: "1Password", url: "https://1password.com" },
            { title: "ChatGPT", url: "https://chat.openai.com" },
            { title: "Zapier", url: "https://zapier.com" },
            { title: "pileofpotential", url: "https://pileofpotential.com" }
        ],
        "Education": [
            { title: "Khan Academy", url: "https://www.khanacademy.org" },
            { title: "Coursera", url: "https://apps.apple.com/us/app/coursera-learn-new-skills/id736535961" },
            { title: "Udemy", url: "https://www.udemy.com" },
            { title: "Duolingo", url: "https://www.duolingo.com" },
            { title: "Skillshare", url: "http://skillshare.eqcm.net/BXYanq" },
            { title: "Quizlet", url: "https://quizlet.com" },
            { title: "Epic", url: "https://www.getepic.com" },
            { title: "Lingvano", url: "https://www.lingvano.com" },
            { title: "Khan Kids", url: "https://www.khanacademy.org/kids" },
            { title: "Babbel", url: "https://www.babbel.com" },
            { title: "Fender Play", url: "https://www.fender.com/play" },
            { title: "Simply Piano", url: "https://www.joytunes.com/simply-piano" },
            { title: "Noggin", url: "https://www.noggin.com" },
            { title: "Lightbot", url: "https://lightbot.com" },
            { title: "ABCMouse", url: "https://www.abcmouse.com" },
            { title: "PBS Kids", url: "https://pbskids.org" },
            { title: "Hooked on Phonics", url: "https://www.hookedonphonics.com" },
            { title: "EdX", url: "https://apps.apple.com/us/app/edx-courses-by-harvard-mit/id945480667" },
            { title: "Brilliant", url: "https://apps.apple.com/us/app/brilliant-solve-learn-grow/id913335252" },
            { title: "Socratic", url: "https://apps.apple.com/app/socratic-by-google/id1014164514" },
            { title: "Nearpod", url: "https://apps.apple.com/app/nearpod/id523540409" },
            { title: "Top Hat", url: "https://apps.apple.com/us/app/top-hat-lecture/id674069291" },
            { title: "Cerego", url: "https://apps.apple.com/us/app/cerego/id688575194" },
            { title: "Voice Dream", url: "https://apps.apple.com/us/app/voice-dream-reader/id496177674" },
            { title: "Asana", url: "https://apps.apple.com/app/asana-organize-tasks-work/id489969512" },
            { title: "My Study Life", url: "https://itunes.apple.com/us/app/my-study-life/id910639339" },
            { title: "Week Plan", url: "https://apps.apple.com/us/app/week-plan-organize-your-life/id1401820342" },
            { title: "Perplexity", url: "https://apps.apple.com/app/perplexity-ask-anything/id1668000334" },
            { title: "Grok", url: "https://apps.apple.com/us/app/grok/id6670324846" },
            { title: "DeepSeek", url: "https://apps.apple.com/app/deepseek/id6477441798" },
            { title: "Claude", url: "https://apps.apple.com/us/app/claude-by-anthropic/id6473753684" },
            { title: "Notion AI", url: "https://apps.apple.com/app/notion-notes-docs-tasks/id1232780281" },
            { title: "Character.ai", url: "https://apps.apple.com/us/app/character-ai-ai-powered-chat/id1671705818" },
            { title: "Blinkist", url: "https://apps.apple.com/us/app/blinkist-book-summaries-daily/id568839295" },
            { title: "DeepStash", url: "https://apps.apple.com/us/app/deepstash-smarter-every-day/id1445023295" },
            { title: "Uptime", url: "https://apps.apple.com/us/app/uptime-get-smarter-stand-out/id1505323328" },
            { title: "Free Books", url: "https://itunes.apple.com/us/app/free-books-23-469-classics/id364612911" },
            { title: "Overdrive", url: "https://itunes.apple.com/us/app/overdrive-library-ebooks-audiobooks/id366869252" },
            { title: "Goodreads", url: "https://itunes.apple.com/us/app/goodreads-book-recommendations/id355833469" },
            { title: "Bookly", url: "https://apps.apple.com/app/bookly-read-more-books/id1085047737" },
            { title: "Free Audiobooks", url: "https://itunes.apple.com/app/free-audiobooks/id1021707022" },
            { title: "Audiobooks", url: "https://itunes.apple.com/us/app/audiobooks/id311507490" },
            { title: "Audible", url: "https://itunes.apple.com/us/app/audiobooks-from-audible/id379693831" },
            { title: "Overcast", url: "https://itunes.apple.com/us/app/overcast-podcast-player/id888422857" }
        ],
        "Utility": [
            { title: "Dropbox", url: "https://www.dropbox.com" },
            { title: "Grammarly", url: "https://www.grammarly.com" },
            { title: "Google Drive", url: "https://www.google.com/drive" },
            { title: "OneDrive", url: "https://www.microsoft.com/en-us/microsoft-365/onedrive" },
            { title: "Microsoft Launcher", url: "https://play.google.com/store/apps/details?id=com.microsoft.launcher" },
            { title: "Network Analyzer", url: "https://play.google.com/store/apps/details?id=net.techet.netanalyzerlite.an" },
            { title: "OtterAI", url: "https://play.google.com/store/apps/details?id=com.aisense.otter" },
            { title: "Speedtest", url: "https://play.google.com/store/apps/details?id=org.zwanoo.android.speedtest" },
            { title: "Steam Link", url: "https://store.steampowered.com/steamlink/about/" },
            { title: "SwiftKey", url: "https://play.google.com/store/apps/details?id=com.touchtype.swiftkey" },
            { title: "Tasker", url: "https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm" },
            { title: "17Track", url: "https://play.google.com/store/apps/details?id=yqtrack.app" },
            { title: "AccuBattery", url: "https://play.google.com/store/apps/details?id=com.digibites.accubattery" },
            { title: "andOTP", url: "https://play.google.com/store/apps/details?id=org.shadowice.flocke.andotp" },
            { title: "AppsFree", url: "https://play.google.com/store/apps/details?id=com.appsfree.android" },
            { title: "Bottled", url: "https://play.google.com/store/apps/details?id=com.bottledapp.bottled" },
            { title: "Bouncer", url: "https://play.google.com/store/apps/details?id=com.samruston.permission" },
            { title: "Changes", url: "https://play.google.com/store/apps/details?id=com.saladevs.changelogclone&hl=en_US" },
            { title: "Cell Mapper", url: "https://play.google.com/store/apps/details?id=cellmapper.net.cellmapper" },
            { title: "CheckMyTrip", url: "https://play.google.com/store/apps/details?id=com.amadeus.cmt.client.android" },
            { title: "Garmin Connect", url: "https://play.google.com/store/apps/details?id=com.garmin.android.apps.connectmobile" },
            { title: "Cronometer", url: "https://play.google.com/store/apps/details?id=com.cronometer.android.gold" },
            { title: "Daylio", url: "https://play.google.com/store/apps/details?id=net.daylio" },
            { title: "DNS Speed Test", url: "https://play.google.com/store/apps/details?id=com.catinthebox.dnsspeedtest" },
            { title: "Dream Catcher", url: "https://play.google.com/store/apps/details?id=com.vojtkovszky.dreamcatcher" },
            { title: "Ecosia", url: "https://play.google.com/store/apps/details?id=com.ecosia.android" },
            { title: "G-Droid", url: "https://f-droid.org/en/packages/org.gdroid.gdroid/" },
            { title: "Family Age", url: "https://play.google.com/store/apps/details?id=com.test.familyage" },
            { title: "Simple Gallery", url: "https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro" },
            { title: "Greenify", url: "https://play.google.com/store/apps/details?id=com.oasisfeng.greenify" },
            { title: "Hackers", url: "https://play.google.com/store/apps/details?id=com.tricksterarts.hackers" },
            { title: "Happy Cow", url: "https://play.google.com/store/apps/details?id=com.hcceg.veg.compassionfree" },
            { title: "Ingred", url: "https://play.google.com/store/apps/details?id=com.zorrosoft.android.ingred" },
            { title: "Inoreader", url: "https://play.google.com/store/apps/details?id=com.innologica.inoreader" }
        ],
        "Health": [
            { title: "Fitbit", url: "https://play.google.com/store/apps/details?id=com.fitbit.FitbitMobile" },
            { title: "Nike Training", url: "https://www.nike.com/us/en_us/ntc-app" },
            { title: "MyFitnessPal", url: "https://www.myfitnesspal.com/apps" },
            { title: "Sleep Cycle", url: "https://sleepcycle.com" },
            { title: "Samsung Health", url: "https://www.similarweb.com/app/google/com.sec.android.app.shealth/" },
            { title: "WeWard", url: "https://www.similarweb.com/app/google/com.weward/" },
            { title: "Finch", url: "https://www.similarweb.com/app/google/com.finch.finch/" },
            { title: "Garmin Connect", url: "https://www.similarweb.com/app/google/com.garmin.android.apps.connectmobile/" },
            { title: "Strava", url: "https://www.similarweb.com/app/google/com.strava/" },
            { title: "Planet Fitness", url: "https://www.similarweb.com/app/google/com.planetfitness/" },
            { title: "CashWalk", url: "https://www.similarweb.com/app/google/com.cashwalklabs.cashwalk/" },
            { title: "Noom", url: "https://www.similarweb.com/app/google/com.wsl.noom/" },
            { title: "PenguPace", url: "https://www.similarweb.com/app/google/com.pengupace/" },
            { title: "Flo", url: "https://www.similarweb.com/app/google/org.iggymedia.periodtracker/" },
            { title: "Dexcom G7", url: "https://www.similarweb.com/app/google/com.dexcom.g7/" },
            { title: "Lose It!", url: "https://www.similarweb.com/app/google/com.fitnow.loseit/" },
            { title: "Texas Benefits", url: "https://www.similarweb.com/app/google/us.tx.state.hhsc.ytbmobile/" },
            { title: "Winwalk", url: "https://www.similarweb.com/app/google/com.winwalk.android/" },
            { title: "Yuka", url: "https://www.similarweb.com/app/google/io.yuka.android/" },
            { title: "healow", url: "https://www.similarweb.com/app/google/com.ecw.healow/" },
            { title: "Kaiser Permanente", url: "https://www.similarweb.com/app/google/org.kp.m/" },
            { title: "WalkPaid", url: "https://www.similarweb.com/app/google/com.walkpaid.walkearn/" },
            { title: "Insight Timer", url: "https://www.similarweb.com/app/google/com.spotlightsix.zentimerlite2/" },
            { title: "Hevy", url: "https://www.similarweb.com/app/google/com.hevy/" },
            { title: "Herlife", url: "https://www.similarweb.com/app/google/app.herlife/" },
            { title: "RENPHO", url: "https://www.similarweb.com/app/google/com.renpho.health/" },
            { title: "LA Fitness", url: "https://www.similarweb.com/app/google/com.lafitness.lafitness/" },
            { title: "AllTrails", url: "https://www.similarweb.com/app/google/com.alltrails.alltrails/" },
            { title: "Noom Vibe", url: "https://www.similarweb.com/app/google/com.socialaudio.wisdom/" },
            { title: "Crunch Fitness", url: "https://www.similarweb.com/app/google/com.ideawork.icrunch/" },
            { title: "WeightWatchers", url: "https://www.similarweb.com/app/google/com.weightwatchers.mobile/" },
            { title: "Glory Fit", url: "https://www.similarweb.com/app/google/com.yc.gloryfit/" },
            { title: "NYC ACCESS HRA", url: "https://www.similarweb.com/app/google/gov.nyc.hra.SelfService/" },
            { title: "ClassPass", url: "https://www.similarweb.com/app/google/com.classpass.classpass/" },
            { title: "Calm", url: "https://www.similarweb.com/app/google/com.calm.android/" },
            { title: "Ambetter", url: "https://www.similarweb.com/app/google/com.centene.dxe.ambetter/" },
            { title: "WHOOP", url: "https://www.similarweb.com/app/google/com.whoop.android/" },
            { title: "Step Counter", url: "https://www.similarweb.com/app/google/pedometer.steptracker.calorieburner.stepcounter/" },
            { title: "VeryFit", url: "https://www.similarweb.com/app/google/com.watch.life/" },
            { title: "Water Tracker", url: "https://www.similarweb.com/app/google/com.water.tracker.remind/" },
            { title: "Evidation", url: "https://www.similarweb.com/app/google/com.achievemint.android/" },
            { title: "MyNetDiary", url: "https://www.similarweb.com/app/google/com.fourtechnologies.mynetdiary.ad/" },
            { title: "Clue", url: "https://www.similarweb.com/app/google/com.clue.android/" },
            { title: "Cronometer", url: "https://www.similarweb.com/app/google/com.cronometer.android.gold/" },
            { title: "Walkify", url: "https://www.similarweb.com/app/google/com.ghamzastudios.walkfi/" },
            { title: "Medisafe", url: "https://www.similarweb.com/app/google/com.medisafe.android.client/" }
        ],
        "Photo": [
            { title: "Canva", url: "https://www.canva.com/photo-editor" },
            { title: "PicsArt", url: "https://picsart.com" },
            { title: "Snapseed", url: "https://apps.apple.com/us/app/snapseed/id439438619" },
            { title: "Lightroom", url: "https://helpx.adobe.com/lightroom-cc/using/premium-features.html" },
            { title: "Afterlight", url: "https://www.afterlight.co" },
            { title: "Apple Photos", url: "https://apps.apple.com/us/app/photos/id1584215428" },
            { title: "Google Photos", url: "https://www.google.com/photos" },
            { title: "Photoroom", url: "https://www.photoroom.com/pricing" },
            { title: "Polarr", url: "https://www.polarr.com" },
            { title: "VSCO", url: "https://www.vsco.co/subscribe/plans" },
            { title: "Photolemur", url: "https://photolemur.com" },
            { title: "Photosense", url: "http://veprit.com/photosense" },
            { title: "Perfectly Clear", url: "http://www.athentech.com" },
            { title: "Akvis Enhancer", url: "http://akvis.com/en/enhancer/index.php" },
            { title: "Enhance Pho.to", url: "http://enhance.pho.to" },
            { title: "Ashampoo", url: "https://www.ashampoo.com/en/usd/pin/1157/multimedia-software/Ashampoo-Photo-Optimizer-6" },
            { title: "PhotoEQ", url: "https://www.softcolorsoftware.com/photoeq/" },
            { title: "DeepArt", url: "https://turbo.deepart.io" }
        ]
    };

    const getIconUrl = (url) => {
        try {
            if (!url) return 'https://img.icons8.com/?size=100&id=123&format=png';
            const domain = new URL(url).hostname;
            return `https://www.google.com/s2/favicons?domain=${domain}&sz=64`;
        } catch (e) {
            return 'https://img.icons8.com/?size=100&id=123&format=png';
        }
    };

    const openApp = (url) => {
        window.open(url, '_blank');
    };

    return (
        <div className="w-full h-[calc(100%-80px)] bg-black text-white overflow-hidden flex flex-col font-sans">
            <div className="p-4 bg-gray-900 border-b border-gray-800">
                <h2 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-400">
                    App Directory
                </h2>
            </div>

            {/* Categories Scroll */}
            <div className="flex overflow-x-auto p-4 gap-3 bg-black no-scrollbar border-b border-gray-800">
                {categories.map(cat => (
                    <button
                        key={cat}
                        onClick={() => setActiveTab(cat)}
                        className={`px-4 py-2 rounded-full whitespace-nowrap text-sm font-medium transition-all ${activeTab === cat
                                ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/30'
                                : 'bg-gray-800 text-gray-400 hover:bg-gray-700'
                            }`}
                    >
                        {cat}
                    </button>
                ))}
            </div>
            {/* Apps Grid */}
            <div className="flex-1 overflow-y-auto pl-5 pt-5 pb-5 pr-10 no-scrollbar custom-scrollbar">
                <div className="grid grid-cols-3 gap-y-10 gap-x-3 justify-items-center">
                    {apps[activeTab] && apps[activeTab].map((app, index) => (
                        <div key={index} className="flex flex-col items-center gap-2 group cursor-pointer" onClick={() => openApp(app.url)}>
                            <div className="w-16 h-16 bg-gradient-to-br from-gray-800 to-gray-900 rounded-[18px] flex items-center justify-center p-3 transition-all duration-500 ease-[cubic-bezier(0.23,1,0.32,1)] hover:scale-110 active:scale-90 shadow-xl border border-white/10 group-hover:border-blue-500/30 overflow-hidden relative">
                                <div className="absolute inset-0 bg-gradient-to-tr from-black/20 to-transparent pointer-events-none"></div>
                                <img
                                    src={getIconUrl(app.url)}
                                    alt={app.title}
                                    className="w-full h-full object-contain rounded-xl relative z-10"
                                    onError={(e) => { e.target.src = 'https://img.icons8.com/ios-filled/50/ffffff/application-window.png' }}
                                />
                            </div>
                            <span className="text-[10px] sm:text-xs text-center text-gray-400 group-hover:text-white line-clamp-1 w-full font-medium px-1">
                                {app.title}
                            </span>
                        </div>
                    ))}
                </div>
                <div className="h-24"></div>
            </div>

        </div>
    );
};

export default AppStoreScreen;
